services:
  urleso.web:
    container_name: urleso-web
    build:
      context: .
      dockerfile: Urleso.Web/Dockerfile
    depends_on:
      urleso.db:
        condition: service_healthy
      urleso.seq:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5238:8080

  urleso.db:
    image: postgres:16.1-alpine
    container_name: urleso-db
    environment:
      - POSTGRES_DB=urleso
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pgpwd4user
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  urleso.seq:
    image: datalust/seq:latest
    container_name: urleso-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5080:80
