version: '3.8'
name: urleso

services:
  urleso.web:
    container_name: urleso-web
    build:
      context: .
      dockerfile: Urleso.Web/Dockerfile
    image: urleso.web:latest
    depends_on:
      urleso.api:
        condition: service_started
      urleso.redirect:
        condition: service_started
      urleso.web.seq:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=${URLESO_ENVIRONMENT}
    volumes:
      - ${WEB_DATA_PROTECTION_KEYS_PATH}:/root/.aspnet/DataProtection-Keys
    ports:
      - ${WEB_PORT}:8080

  urleso.api:
    container_name: urleso-api
    build:
      context: .
      dockerfile: Urleso.Api/Dockerfile
    image: urleso.api:latest
    depends_on:
      urleso.mirgations:
        condition: service_completed_successfully
      urleso.api.seq:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=${URLESO_ENVIRONMENT}
      - CONNECTION_STRINGS_POSTGRESQL=Host=urleso-db;Port=5432;Database=${DATABASE_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD}
      - REDIRECT_BASE_ADDRESS=${REDIRECT_PUBLIC_URL}
    ports:
      - ${API_PORT}:8080

  urleso.redirect:
    container_name: urleso-redirect
    build:
      context: .
      dockerfile: Urleso.Redirect/Dockerfile
    image: urleso.redirect:latest
    depends_on:
      urleso.mirgations:
        condition: service_completed_successfully
      urleso.redirect.seq:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=${URLESO_ENVIRONMENT}
      - CONNECTION_STRINGS_POSTGRESQL=Host=urleso-db;Port=5432;Database=${DATABASE_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD}
    ports:
      - ${REDIRECT_PORT}:8080

  urleso.mirgations:
    container_name: urleso-migrations
    build:
      context: .
      dockerfile: Urleso.DatabaseMigrator/Dockerfile
    image: urleso.migrations:latest
    depends_on:
      urleso.db:
        condition: service_healthy
    environment:
      - DOTNET_ENVIRONMENT=${URLESO_ENVIRONMENT}
      - CONNECTION_STRINGS_POSTGRESQL=Host=urleso-db;Port=5432;Database=${DATABASE_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD}

  urleso.db:
    image: postgres:16.1-alpine
    container_name: urleso-db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${DATABASE_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  urleso.web.seq:
    image: datalust/seq:2023.4
    container_name: urleso-web-seq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ${WEB_SEQ_DATA_PATH}:/data
    ports:
      - ${WEB_SEQ_PORT}:80

  urleso.api.seq:
    image: datalust/seq:2023.4
    container_name: urleso-api-seq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ${API_SEQ_DATA_PATH}:/data
    ports:
      - ${API_SEQ_PORT}:80

  urleso.redirect.seq:
    image: datalust/seq:2023.4
    container_name: urleso-redirect-seq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ${REDIRECT_SEQ_DATA_PATH}:/data
    ports:
      - ${REDIRECT_SEQ_PORT}:80
